### ISSUE TITLE
Want SQL file to create one in our own local db

### ISSUE THREAD

**Issue by ChayanitBhateja** [hardikpnsp/ocrs#1]
Please link or send the sql file with which you've made your project. I want to know the tables and the structure of db so to use the same schema in our own db.

**Comment by hardikpnsp** [comment]
It has been almost 3 years since I worked on this project but as far as I remember you can make use of the migrations. You probably don't need to create a database schema manually.

Reference: [Django migrations](https://docs.djangoproject.com/en/3.1/topics/migrations/)

**Comment by ChayanitBhateja** [comment]
I was actually not aware of this. I am helping someone with the project.

Afterwards I read about migrations I got to know about that then.

Anyways anyhow, Thankyou very much for your active support. It means a lot
to me.

Thankyou and regards,
Chayanit Bhateja
